import type { WishItem } from "@/types/wish";

export const MOCK_WISHES: WishItem[] = [
  {
    id: "1",
    title: "Đôi giày sneaker pastel",
    url: "https://example.com/sneaker",
    image_url: null,
    price: 1_290_000,
    currency: "VND",
    priority: "MUST_HAVE",
    note: "Đi cùng outfit hồng kem siêu hợp ✨",
    is_secretly_buying: false,
    is_gifted: false,
    gifted_at: null,
    gift_message: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Bộ ly sứ Hàn Quốc",
    url: null,
    image_url: null,
    price: 480_000,
    currency: "VND",
    priority: "REALLY_WANT",
    note: "Để hai đứa mỗi sáng cùng uống matcha latte ☕",
    is_secretly_buying: false,
    is_gifted: false,
    gifted_at: null,
    gift_message: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Chuyến đi Đà Lạt cuối năm",
    url: null,
    image_url: null,
    price: null,
    currency: "VND",
    priority: "WANT",
    note: "Mơ mãi rồi 🌲",
    is_secretly_buying: false,
    is_gifted: true,
    gifted_at: "2025-12-24T00:00:00.000Z",
    gift_message: "Đêm Giáng sinh năm nay mình đi nhé. Anh đặt phòng rồi 🎄",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
